version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: juice-bar-backend
    volumes:
      - juice-bar-data:/app/uploads
      - ./backend/pos.db:/app/pos.db
    environment:
      - ALLOWED_ORIGINS=http://localhost:80,http://localhost,http://127.0.0.1
      - SECRET_KEY=your_very_secret_key_here_change_in_production
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    container_name: juice-bar-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  juice-bar-data:
